# Generated by Django 5.2.17 on 2026-08-25 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('companies', '0001_initial'),
        ('customers', '0002_initial'),
        ('reps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="Machine name, e.g. 'warranty_months'.", max_length=64)),
                ('label', models.CharField(help_text='Display name shown in the UI.', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_custom_field_definitions', to='companies.company')),
            ],
            options={
                'db_table': 'custom_field_definition',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('sku', models.CharField(blank=True, default='', max_length=64)),
                ('barcode', models.CharField(blank=True, default='', help_text='GTIN / UPC / EAN, if applicable.', max_length=64)),
                ('brand', models.CharField(blank=True, default='', max_length=128)),
                ('image', models.FileField(blank=True, null=True, upload_to='products/')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('weight_unit', models.CharField(blank=True, default='', max_length=8)),
                ('length', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('dimension_unit', models.CharField(blank=True, default='', max_length=8)),
                ('reorder_point', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('reorder_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('is_taxable', models.BooleanField(default=True)),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage, e.g. 21.00 for 21%.', max_digits=5, null=True)),
                ('is_sellable', models.BooleanField(default=True)),
                ('is_purchasable', models.BooleanField(default=True)),
                ('external_reference', models.CharField(blank=True, default='', help_text='ID in an external/legacy system, for integrations.', max_length=128)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='companies.company')),
                ('unit', models.ForeignKey(help_text='Required. Pick from the predefined catalog, not free text.', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='common.unitofmeasure')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.customfielddefinition')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='products.product')),
            ],
            options={
                'db_table': 'custom_field_value',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='companies.company')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.productcategory')),
            ],
            options={
                'verbose_name_plural': 'product categories',
                'db_table': 'product_category',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productcategory'),
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_type', models.CharField(choices=[('standard', 'Standard'), ('wholesale', 'Wholesale'), ('cost', 'Cost')], default='standard', max_length=16)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_default', models.BooleanField(default=False, help_text="Marks the default currency to show/use for this product's general price.")),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_prices', to='common.currency')),
                ('customer_category', models.ForeignKey(blank=True, help_text='Leave blank for the general price. Set to override for that customer category.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='customers.customercategory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.product')),
            ],
            options={
                'db_table': 'product_price',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, default='')),
                ('kind', models.CharField(blank=True, default='', max_length=64)),
                ('owner_type', models.CharField(choices=[('company', 'Company'), ('rep', 'Rep')], max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='companies.company')),
                ('rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='reps.rep')),
            ],
            options={
                'db_table': 'warehouse',
            },
        ),
        migrations.CreateModel(
            name='ProductWarehouseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_warehouse_stocks', to='companies.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stocks', to='products.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stocks', to='products.warehouse')),
            ],
            options={
                'db_table': 'product_warehouse_stock',
            },
        ),
        migrations.AddIndex(
            model_name='customfielddefinition',
            index=models.Index(fields=['company'], name='cfd_company_idx'),
        ),
        migrations.AddConstraint(
            model_name='customfielddefinition',
            constraint=models.UniqueConstraint(fields=('company', 'key'), name='custom_field_def_company_key_uniq'),
        ),
        migrations.AddIndex(
            model_name='customfieldvalue',
            index=models.Index(fields=['product'], name='cfv_product_idx'),
        ),
        migrations.AddConstraint(
            model_name='customfieldvalue',
            constraint=models.UniqueConstraint(fields=('product', 'definition'), name='custom_field_value_uniq'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['company'], name='product_cat_company_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['parent'], name='product_cat_parent_idx'),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(fields=('company', 'parent', 'name'), name='product_category_company_parent_name_uniq'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company'], name='product_company_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='product_category_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['barcode'], name='product_barcode_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('sku', ''), _negated=True), fields=('company', 'sku'), name='product_company_sku_uniq'),
        ),
        migrations.AddIndex(
            model_name='productprice',
            index=models.Index(fields=['product'], name='product_price_product_idx'),
        ),
        migrations.AddIndex(
            model_name='productprice',
            index=models.Index(fields=['currency'], name='product_price_currency_idx'),
        ),
        migrations.AddIndex(
            model_name='productprice',
            index=models.Index(fields=['customer_category'], name='product_price_cust_cat_idx'),
        ),
        migrations.AddConstraint(
            model_name='productprice',
            constraint=models.UniqueConstraint(condition=models.Q(('customer_category__isnull', True)), fields=('product', 'currency', 'price_type'), name='product_price_general_uniq'),
        ),
        migrations.AddConstraint(
            model_name='productprice',
            constraint=models.UniqueConstraint(condition=models.Q(('customer_category__isnull', False)), fields=('product', 'currency', 'price_type', 'customer_category'), name='product_price_customer_category_uniq'),
        ),
        migrations.AddConstraint(
            model_name='productprice',
            constraint=models.UniqueConstraint(condition=models.Q(('customer_category__isnull', True), ('is_default', True)), fields=('product',), name='product_price_one_default'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['company'], name='warehouse_company_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['rep'], name='warehouse_rep_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['company', 'owner_type'], name='wh_company_owner_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('owner_type', 'company'), ('rep__isnull', True)), models.Q(('owner_type', 'rep'), ('rep__isnull', False)), _connector='OR'), name='warehouse_owner_matches_rep'),
        ),
        migrations.AddIndex(
            model_name='productwarehousestock',
            index=models.Index(fields=['company'], name='pws_company_idx'),
        ),
        migrations.AddIndex(
            model_name='productwarehousestock',
            index=models.Index(fields=['warehouse'], name='pws_warehouse_idx'),
        ),
        migrations.AddConstraint(
            model_name='productwarehousestock',
            constraint=models.UniqueConstraint(fields=('product', 'warehouse'), name='product_warehouse_stock_uniq'),
        ),
    ]
