# Generated by Django 5.2.17 on 2026-08-14 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('reps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'unit_of_measure',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, default='', max_length=64)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('image', models.FileField(blank=True, null=True, upload_to='products/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='companies.company')),
                ('unit', models.ForeignKey(help_text='Required. Pick from the predefined catalog, not free text.', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.unitofmeasure')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, default='')),
                ('kind', models.CharField(blank=True, default='', max_length=64)),
                ('owner_type', models.CharField(choices=[('company', 'Company'), ('rep', 'Rep')], max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='companies.company')),
                ('rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='reps.rep')),
            ],
            options={
                'db_table': 'warehouse',
            },
        ),
        migrations.CreateModel(
            name='ProductWarehouseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_warehouse_stocks', to='companies.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stocks', to='products.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stocks', to='products.warehouse')),
            ],
            options={
                'db_table': 'product_warehouse_stock',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company'], name='product_company_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('sku', ''), _negated=True), fields=('company', 'sku'), name='product_company_sku_uniq'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['company'], name='warehouse_company_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['rep'], name='warehouse_rep_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['company', 'owner_type'], name='wh_company_owner_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('owner_type', 'company'), ('rep__isnull', True)), models.Q(('owner_type', 'rep'), ('rep__isnull', False)), _connector='OR'), name='warehouse_owner_matches_rep'),
        ),
        migrations.AddIndex(
            model_name='productwarehousestock',
            index=models.Index(fields=['company'], name='pws_company_idx'),
        ),
        migrations.AddIndex(
            model_name='productwarehousestock',
            index=models.Index(fields=['warehouse'], name='pws_warehouse_idx'),
        ),
        migrations.AddConstraint(
            model_name='productwarehousestock',
            constraint=models.UniqueConstraint(fields=('product', 'warehouse'), name='product_warehouse_stock_uniq'),
        ),
    ]
