# Generated by Django 5.2.17 on 2026-08-29 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('products', '0003_product_status'),
        # StockMovement moved from `orders` to `products` (inventory owns the
        # ledger; both `invoices` and `orders` write to it). Both models map to
        # the same `stock_movement` table, so the old one must be dropped before
        # this CREATE TABLE runs.
        ('orders', '0003_remove_stockmovement_order_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, help_text="Signed, in the product's UnitOfMeasure. Positive = inbound, negative = outbound.", max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=3, help_text='Warehouse quantity for this product immediately after the movement.', max_digits=14)),
                ('movement_type', models.CharField(choices=[('initial', 'Initial stock'), ('incoming', 'Incoming invoice receipt'), ('transfer_out', 'Stock transfer leaving the company warehouse'), ('transfer_in', 'Stock transfer entering the rep warehouse'), ('sale_out', 'Sales invoice leaving the rep warehouse'), ('return_in', 'Return received into a warehouse'), ('adjustment', 'Manual adjustment')], max_length=32)),
                ('source_type', models.CharField(choices=[('incoming_invoice', 'Incoming invoice'), ('stock_transfer', 'Stock transfer'), ('sales_invoice', 'Sales invoice'), ('return_invoice', 'Return invoice'), ('manual', 'Manual adjustment')], max_length=32)),
                ('source_id', models.BigIntegerField(blank=True, help_text='PK of the source document. Null only for manual adjustments.', null=True)),
                ('source_number', models.CharField(blank=True, default='', help_text='Document number snapshot, so the ledger reads without joins.', max_length=32)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='companies.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='products.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='products.warehouse')),
            ],
            options={
                'db_table': 'stock_movement',
                'indexes': [models.Index(fields=['company'], name='stock_movement_company_idx'), models.Index(fields=['warehouse'], name='stock_movement_wh_idx'), models.Index(fields=['warehouse', 'product'], name='stock_movement_wh_prod_idx'), models.Index(fields=['source_type', 'source_id'], name='stock_movement_source_idx'), models.Index(fields=['created_at'], name='stock_movement_created_idx')],
            },
        ),
    ]
