# Generated by Django 5.2.17 on 2026-08-14 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('customers', '0001_initial'),
        ('invoices', '0001_initial'),
        ('products', '0001_initial'),
        ('reps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('rep_to_company', 'Rep → Company'), ('customer_to_company', 'Customer → Company')], max_length=32)),
                ('status', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='companies.company')),
                ('customer', models.ForeignKey(blank=True, help_text='Set for customer→company orders.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.customer')),
                ('fulfilling_rep', models.ForeignKey(blank=True, help_text='Nullable. Required to leave pending_rep_assignment.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fulfilling_orders', to='reps.rep')),
                ('placing_rep', models.ForeignKey(blank=True, help_text="Set for rep→company orders (the 'created by' rep).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='placed_orders', to='reps.rep')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='companies.company')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product')),
                ('unit', models.ForeignKey(help_text='Snapshot of Product.unit at line creation.', on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.unitofmeasure')),
            ],
            options={
                'db_table': 'order_item',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, help_text="Signed, in the product's UnitOfMeasure. Positive = inbound, negative = outbound.", max_digits=14)),
                ('movement_type', models.CharField(choices=[('initial', 'Initial stock'), ('incoming', 'Incoming invoice receipt'), ('order_out', 'Stock leaving a warehouse (order)'), ('order_in', 'Stock entering a warehouse (order)'), ('return_in', 'Return received into a warehouse'), ('return_out', 'Return leaving a warehouse'), ('adjustment', 'Manual adjustment')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='companies.company')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='invoices.invoice')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='products.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='products.warehouse')),
            ],
            options={
                'db_table': 'stock_movement',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['company'], name='order_company_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['company', 'status'], name='order_company_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='order_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer'], name='order_customer_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['placing_rep'], name='order_placing_rep_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['fulfilling_rep'], name='order_fulfilling_rep_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['company'], name='order_item_company_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='order_item_order_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['company'], name='stock_movement_company_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['warehouse'], name='stock_movement_wh_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['warehouse', 'product'], name='stock_movement_wh_prod_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['order'], name='stock_movement_order_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['created_at'], name='stock_movement_created_idx'),
        ),
    ]
