# Generated by Django 5.2.17 on 2026-08-29 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auditlog_documentsequence_idempotencykey'),
        ('companies', '0001_initial'),
        ('customers', '0002_initial'),
        ('invoices', '0003_remove_invoice_company_remove_invoice_rep_and_more'),
        ('orders', '0002_initial'),
        ('products', '0003_product_status'),
        ('reps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovement',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='company',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='company',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='warehouse',
        ),
        migrations.CreateModel(
            name='CustomerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(help_text='The company being browsed in the customer app.', on_delete=django.db.models.deletion.CASCADE, related_name='customer_requests', to='companies.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='customers.customer')),
                ('fulfilled_by_invoice', models.ForeignKey(blank=True, help_text='Set when a rep links a delivery to this request. Optional by design.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_requests', to='invoices.salesinvoice')),
                ('rep', models.ForeignKey(blank=True, help_text='Assigned rep notified at creation time, if the customer has one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_requests', to='reps.rep')),
            ],
            options={
                'db_table': 'customer_request',
            },
        ),
        migrations.CreateModel(
            name='CustomerRequestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='products.product')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.customerrequest')),
                ('unit', models.ForeignKey(help_text='Snapshot of Product.unit at line creation.', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='common.unitofmeasure')),
            ],
            options={
                'db_table': 'customer_request_line',
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending admin review'), ('modified_by_admin', 'Modified by admin'), ('pending_rep_confirmation', 'Pending rep confirmation'), ('confirmed', 'Confirmed'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='pending', max_length=32)),
                ('requested_at', models.DateTimeField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_stock_transfers', to='companies.subuser')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transfers', to='companies.company')),
                ('destination_warehouse', models.ForeignKey(help_text='Rep warehouse the goods arrive in.', on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='products.warehouse')),
                ('rep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfers', to='reps.rep')),
                ('source_warehouse', models.ForeignKey(help_text='Company warehouse the goods leave.', on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='products.warehouse')),
            ],
            options={
                'db_table': 'stock_transfer',
            },
        ),
        migrations.CreateModel(
            name='StockTransferLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_qty', models.DecimalField(decimal_places=3, max_digits=14)),
                ('approved_qty', models.DecimalField(blank=True, decimal_places=3, help_text='Null until an admin approves or modifies the transfer.', max_digits=14, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='products.product')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.stocktransfer')),
                ('unit', models.ForeignKey(help_text='Snapshot of Product.unit at line creation.', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='common.unitofmeasure')),
            ],
            options={
                'db_table': 'stock_transfer_line',
            },
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='StockMovement',
        ),
        migrations.AddIndex(
            model_name='customerrequest',
            index=models.Index(fields=['company'], name='cust_request_company_idx'),
        ),
        migrations.AddIndex(
            model_name='customerrequest',
            index=models.Index(fields=['company', 'status'], name='cust_request_status_idx'),
        ),
        migrations.AddIndex(
            model_name='customerrequest',
            index=models.Index(fields=['customer'], name='cust_request_customer_idx'),
        ),
        migrations.AddIndex(
            model_name='customerrequest',
            index=models.Index(fields=['rep'], name='cust_request_rep_idx'),
        ),
        migrations.AddIndex(
            model_name='customerrequest',
            index=models.Index(fields=['created_at'], name='cust_request_created_idx'),
        ),
        migrations.AddIndex(
            model_name='customerrequestline',
            index=models.Index(fields=['company'], name='cust_req_line_company_idx'),
        ),
        migrations.AddIndex(
            model_name='customerrequestline',
            index=models.Index(fields=['request'], name='cust_req_line_request_idx'),
        ),
        migrations.AddConstraint(
            model_name='customerrequestline',
            constraint=models.UniqueConstraint(fields=('request', 'product'), name='customer_request_line_product_uniq'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['company'], name='transfer_company_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['company', 'status'], name='transfer_status_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['rep'], name='transfer_rep_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['requested_at'], name='transfer_requested_idx'),
        ),
        migrations.AddConstraint(
            model_name='stocktransfer',
            constraint=models.UniqueConstraint(fields=('company', 'number'), name='stock_transfer_company_number_uniq'),
        ),
        migrations.AddIndex(
            model_name='stocktransferline',
            index=models.Index(fields=['company'], name='transfer_line_company_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransferline',
            index=models.Index(fields=['transfer'], name='transfer_line_transfer_idx'),
        ),
        migrations.AddConstraint(
            model_name='stocktransferline',
            constraint=models.UniqueConstraint(fields=('transfer', 'product'), name='stock_transfer_line_product_uniq'),
        ),
    ]
