# Generated by Django 5.2.17 on 2026-08-31 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_stockmovement_order_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrequest',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerrequest',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerrequest',
            name='rejection_reason',
            field=models.CharField(blank=True, default='', help_text='Optional note the rep leaves when turning a request down.', max_length=255),
        ),
        migrations.AlterField(
            model_name='customerrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted by rep'), ('fulfilled', 'Fulfilled'), ('rejected', 'Rejected by rep'), ('cancelled', 'Cancelled by customer')], default='pending', max_length=16),
        ),
    ]
