# Generated by Django 5.2.17 on 2026-08-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_customerrequest_accepted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransfer',
            name='pickup_within_hours',
            field=models.PositiveSmallIntegerField(blank=True, help_text='How long after requesting the rep expects to collect. Null on a dispatch, where the office started it and no window was promised.', null=True),
        ),
    ]
