# Generated by Django 5.2.17 on 2026-08-25 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('customers', '0001_initial'),
        ('reps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='assigned_reps',
            field=models.ManyToManyField(blank=True, help_text='Reps from any company can be assigned to this customer', related_name='assigned_customers', through='reps.RepCustomerAssignment', to='reps.rep'),
        ),
        migrations.AddField(
            model_name='customercategory',
            name='company',
            field=models.ForeignKey(blank=True, help_text='NULL = global default category, otherwise company-specific', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_categories', to='companies.company'),
        ),
        migrations.AddField(
            model_name='customercategoryassignment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='customers.customercategory'),
        ),
        migrations.AddField(
            model_name='customercategoryassignment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_category_assignments', to='companies.company'),
        ),
        migrations.AddField(
            model_name='customercategoryassignment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_assignments', to='customers.customer'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone'], name='customer_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['referral_code_used'], name='customer_referral_code_idx'),
        ),
        migrations.AddIndex(
            model_name='customercategory',
            index=models.Index(fields=['company'], name='customer_category_company_idx'),
        ),
        migrations.AddIndex(
            model_name='customercategory',
            index=models.Index(fields=['is_active'], name='customer_category_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='customercategory',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='customer_category_company_name_uniq'),
        ),
        migrations.AddIndex(
            model_name='customercategoryassignment',
            index=models.Index(fields=['customer', 'company'], name='cust_cat_assign_cust_comp_idx'),
        ),
        migrations.AddIndex(
            model_name='customercategoryassignment',
            index=models.Index(fields=['company'], name='cust_cat_assign_company_idx'),
        ),
        migrations.AddIndex(
            model_name='customercategoryassignment',
            index=models.Index(fields=['category'], name='cust_cat_assign_category_idx'),
        ),
        migrations.AddConstraint(
            model_name='customercategoryassignment',
            constraint=models.UniqueConstraint(fields=('customer', 'company'), name='customer_category_assignment_uniq'),
        ),
    ]
