# Generated by Django 5.2.17 on 2026-08-31 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, default='', help_text='Free text as the rep would say it — street, neighbourhood, city. Separate from latitude/longitude: a pin gets you there, this is what a person reads on a route list.', max_length=255),
        ),
    ]
