# Generated by Django 5.2.17 on 2026-08-14 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('currency', models.CharField(max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'company',
                'indexes': [models.Index(fields=['slug'], name='company_slug_idx')],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='companies.company')),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=64)),
                ('can_view', models.BooleanField(default=False)),
                ('can_action', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to='companies.company')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='companies.role')),
            ],
            options={
                'db_table': 'module_permission',
            },
        ),
        migrations.CreateModel(
            name='SubUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_owner', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subusers', to='companies.company')),
                ('role', models.ForeignKey(blank=True, help_text='Null allowed only for is_owner=True (implicit full access).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subusers', to='companies.role')),
            ],
            options={
                'db_table': 'subuser',
            },
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['company'], name='role_company_idx'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='role_company_name_uniq'),
        ),
        migrations.AddIndex(
            model_name='modulepermission',
            index=models.Index(fields=['company'], name='modperm_company_idx'),
        ),
        migrations.AddConstraint(
            model_name='modulepermission',
            constraint=models.UniqueConstraint(fields=('role', 'module'), name='modperm_role_module_uniq'),
        ),
        migrations.AddIndex(
            model_name='subuser',
            index=models.Index(fields=['company'], name='subuser_company_idx'),
        ),
        migrations.AddIndex(
            model_name='subuser',
            index=models.Index(fields=['phone'], name='subuser_phone_idx'),
        ),
        migrations.AddConstraint(
            model_name='subuser',
            constraint=models.UniqueConstraint(fields=('company', 'phone'), name='subuser_company_phone_uniq'),
        ),
        migrations.AddConstraint(
            model_name='subuser',
            constraint=models.UniqueConstraint(condition=models.Q(('is_owner', True)), fields=('company',), name='subuser_one_owner_per_company'),
        ),
    ]
