# Generated by Django 5.2.17 on 2026-08-14 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('products', '0001_initial'),
        ('reps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(choices=[('incoming', 'Incoming'), ('return', 'Return')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='companies.company')),
                ('rep', models.ForeignKey(blank=True, help_text='Set for return invoices initiated by a rep.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='reps.rep')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='products.warehouse')),
            ],
            options={
                'db_table': 'invoice',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='companies.company')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='products.product')),
                ('unit', models.ForeignKey(help_text='Snapshot of Product.unit at line creation.', on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='products.unitofmeasure')),
            ],
            options={
                'db_table': 'invoice_item',
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company'], name='invoice_company_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_type'], name='invoice_type_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['warehouse'], name='invoice_warehouse_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['company'], name='invoice_item_company_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['invoice'], name='invoice_item_invoice_idx'),
        ),
    ]
