# Generated by Django 5.2.17 on 2026-08-29 20:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auditlog_documentsequence_idempotencykey'),
        ('companies', '0001_initial'),
        ('customers', '0002_initial'),
        ('invoices', '0002_initial'),
        ('products', '0003_product_status'),
        ('reps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='company',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='rep',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='company',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='unit',
        ),
        migrations.CreateModel(
            name='IncomingInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=32)),
                ('date', models.DateTimeField()),
                ('supplier_ref', models.CharField(blank=True, default='', help_text='Free text naming the supplier or parent company.', max_length=255)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('tax_registration_no', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('notes', models.TextField(blank=True, default='')),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_invoices', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_invoices', to='companies.subuser')),
                ('warehouse', models.ForeignKey(help_text='Company warehouse the goods are received into.', on_delete=django.db.models.deletion.PROTECT, related_name='incoming_invoices', to='products.warehouse')),
            ],
            options={
                'db_table': 'incoming_invoice',
            },
        ),
        migrations.CreateModel(
            name='IncomingInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoices.incominginvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='products.product')),
                ('unit', models.ForeignKey(help_text='Snapshot of Product.unit at line creation.', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='common.unitofmeasure')),
            ],
            options={
                'db_table': 'incoming_invoice_line',
            },
        ),
        migrations.CreateModel(
            name='InvoiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(blank=True, default='', help_text='Legal name printed on invoices. Falls back to Company.name when blank.', max_length=255)),
                ('tax_registration_no', models.CharField(blank=True, default='', max_length=64)),
                ('address', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('overdue_threshold_days', models.PositiveIntegerField(default=7, help_text='Days after which an unsettled sales invoice counts as overdue (§5).')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_settings', to='companies.company')),
            ],
            options={
                'verbose_name_plural': 'invoice settings',
                'db_table': 'invoice_settings',
            },
        ),
        migrations.CreateModel(
            name='ReturnInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=32)),
                ('date', models.DateTimeField()),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('tax_registration_no', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued')], default='draft', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('overage_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Derived: (returned + paid) - total on the parent invoice, floored at 0.', max_digits=14)),
                ('refund_method', models.CharField(blank=True, choices=[('cash_refunded_by_rep', 'Cash refunded by rep'), ('deferred_customer_credit', 'Deferred customer credit')], default='', help_text='Required before issuing when this return creates an overage.', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_invoices', to='companies.company')),
                ('rep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_invoices', to='reps.rep')),
                ('warehouse', models.ForeignKey(help_text="Where the goods physically land. The rep's warehouse by default; an admin can route defective goods to a company warehouse instead.", on_delete=django.db.models.deletion.PROTECT, related_name='return_invoices', to='products.warehouse')),
            ],
            options={
                'db_table': 'return_invoice',
            },
        ),
        migrations.CreateModel(
            name='RepCashAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text="Signed. Negative reduces the rep's expected cash-in (e.g. a refund paid out).", max_digits=14)),
                ('reason', models.CharField(max_length=64)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rep_cash_adjustments', to='companies.company')),
                ('rep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_adjustments', to='reps.rep')),
                ('return_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_adjustments', to='invoices.returninvoice')),
            ],
            options={
                'db_table': 'rep_cash_adjustment',
            },
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=32)),
                ('date', models.DateTimeField()),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('tax_registration_no', models.CharField(blank=True, default='', max_length=64)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Derived: sum of linked payment_collections.', max_digits=14)),
                ('returned_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Derived: sum of linked issued return_invoices.', max_digits=14)),
                ('balance_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Derived: max(0, total - paid - returned). Never negative.', max_digits=14)),
                ('status', models.CharField(choices=[('fully_paid', 'Fully paid'), ('partially_paid', 'Partially paid'), ('deferred', 'Deferred')], default='deferred', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_invoices', to='companies.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='customers.customer')),
                ('rep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='reps.rep')),
                ('warehouse', models.ForeignKey(help_text='Rep warehouse the goods leave from.', on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='products.warehouse')),
            ],
            options={
                'db_table': 'sales_invoice',
            },
        ),
        migrations.AddField(
            model_name='returninvoice',
            name='sales_invoice',
            field=models.ForeignKey(help_text='Required — a return is always a credit note against a sale.', on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='invoices.salesinvoice'),
        ),
        migrations.CreateModel(
            name='PendingCustomerCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_credits', to='companies.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pending_credits', to='customers.customer')),
                ('source_return_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='invoices.returninvoice')),
                ('applied_to_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applied_credits', to='invoices.salesinvoice')),
            ],
            options={
                'db_table': 'pending_customer_credit',
            },
        ),
        migrations.CreateModel(
            name='PaymentCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('collected_at', models.DateTimeField()),
                ('source', models.CharField(choices=[('cash', 'Cash collected by rep'), ('customer_credit', 'Applied from a pending customer credit')], default='cash', help_text="Cash counts toward the rep's expected cash-in; credit does not.", max_length=16)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collected_by', models.ForeignKey(blank=True, help_text='Null when an admin records the payment rather than a rep.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_collections', to='reps.rep')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_collections', to='companies.company')),
                ('applied_credit', models.ForeignKey(blank=True, help_text='Set when this row records a customer credit being applied (§3.7 rule 2).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='invoices.pendingcustomercredit')),
                ('sales_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='invoices.salesinvoice')),
            ],
            options={
                'db_table': 'payment_collection',
            },
        ),
        migrations.CreateModel(
            name='SalesInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoices.salesinvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='products.product')),
                ('unit', models.ForeignKey(help_text='Snapshot of Product.unit at line creation.', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='common.unitofmeasure')),
            ],
            options={
                'db_table': 'sales_invoice_line',
            },
        ),
        migrations.CreateModel(
            name='ReturnInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='products.product')),
                ('return_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoices.returninvoice')),
                ('unit', models.ForeignKey(help_text='Snapshot of Product.unit at line creation.', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='common.unitofmeasure')),
                ('sales_invoice_line', models.ForeignKey(help_text='The sold line being credited. Source of unit_price and of the returnable cap.', on_delete=django.db.models.deletion.PROTECT, related_name='return_lines', to='invoices.salesinvoiceline')),
            ],
            options={
                'db_table': 'return_invoice_line',
            },
        ),
    ]
