# Generated by Django 5.2.17 on 2026-08-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_remove_invoice_company_remove_invoice_rep_and_more'),
        ('orders', '0003_remove_stockmovement_order_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
        migrations.AddIndex(
            model_name='incominginvoice',
            index=models.Index(fields=['company'], name='inc_invoice_company_idx'),
        ),
        migrations.AddIndex(
            model_name='incominginvoice',
            index=models.Index(fields=['company', 'status'], name='inc_invoice_status_idx'),
        ),
        migrations.AddIndex(
            model_name='incominginvoice',
            index=models.Index(fields=['date'], name='inc_invoice_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='incominginvoice',
            constraint=models.UniqueConstraint(fields=('company', 'number'), name='incoming_invoice_company_number_uniq'),
        ),
        migrations.AddIndex(
            model_name='incominginvoiceline',
            index=models.Index(fields=['company'], name='inc_invoice_line_company_idx'),
        ),
        migrations.AddIndex(
            model_name='incominginvoiceline',
            index=models.Index(fields=['invoice'], name='inc_invoice_line_invoice_idx'),
        ),
        migrations.AddIndex(
            model_name='repcashadjustment',
            index=models.Index(fields=['company'], name='cash_adj_company_idx'),
        ),
        migrations.AddIndex(
            model_name='repcashadjustment',
            index=models.Index(fields=['rep'], name='cash_adj_rep_idx'),
        ),
        migrations.AddIndex(
            model_name='repcashadjustment',
            index=models.Index(fields=['created_at'], name='cash_adj_created_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['company'], name='sales_invoice_company_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['company', 'status'], name='sales_invoice_status_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['rep'], name='sales_invoice_rep_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['customer'], name='sales_invoice_customer_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['created_at'], name='sales_invoice_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoice',
            constraint=models.UniqueConstraint(fields=('company', 'number'), name='sales_invoice_company_number_uniq'),
        ),
        migrations.AddIndex(
            model_name='returninvoice',
            index=models.Index(fields=['company'], name='return_invoice_company_idx'),
        ),
        migrations.AddIndex(
            model_name='returninvoice',
            index=models.Index(fields=['sales_invoice'], name='return_invoice_sales_idx'),
        ),
        migrations.AddIndex(
            model_name='returninvoice',
            index=models.Index(fields=['rep'], name='return_invoice_rep_idx'),
        ),
        migrations.AddIndex(
            model_name='returninvoice',
            index=models.Index(fields=['company', 'status'], name='return_invoice_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='returninvoice',
            constraint=models.UniqueConstraint(fields=('company', 'number'), name='return_invoice_company_number_uniq'),
        ),
        migrations.AddIndex(
            model_name='pendingcustomercredit',
            index=models.Index(fields=['company'], name='credit_company_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingcustomercredit',
            index=models.Index(fields=['customer', 'status'], name='credit_customer_status_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingcustomercredit',
            index=models.Index(fields=['source_return_invoice'], name='credit_return_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentcollection',
            index=models.Index(fields=['company'], name='payment_company_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentcollection',
            index=models.Index(fields=['sales_invoice'], name='payment_invoice_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentcollection',
            index=models.Index(fields=['collected_by'], name='payment_rep_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentcollection',
            index=models.Index(fields=['collected_at'], name='payment_collected_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoiceline',
            index=models.Index(fields=['company'], name='sales_line_company_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoiceline',
            index=models.Index(fields=['invoice'], name='sales_line_invoice_idx'),
        ),
        migrations.AddIndex(
            model_name='returninvoiceline',
            index=models.Index(fields=['company'], name='return_line_company_idx'),
        ),
        migrations.AddIndex(
            model_name='returninvoiceline',
            index=models.Index(fields=['return_invoice'], name='return_line_invoice_idx'),
        ),
        migrations.AddIndex(
            model_name='returninvoiceline',
            index=models.Index(fields=['sales_invoice_line'], name='return_line_sales_line_idx'),
        ),
    ]
