# Generated by Django 5.2.17 on 2026-08-30 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_delete_invoice_delete_invoiceitem_and_more'),
        ('products', '0004_stockmovement'),
        ('reps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returninvoice',
            name='rep',
            field=models.ForeignKey(blank=True, help_text='Inherited from the sale being credited, so it is null when crediting a company-direct sale.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_invoices', to='reps.rep'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='rep',
            field=models.ForeignKey(blank=True, help_text='Null for a company-direct sale — a customer buying from the company itself, with no rep involved. Set for the normal field sale.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='reps.rep'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='warehouse',
            field=models.ForeignKey(help_text="Warehouse the goods leave: the rep's van for a field sale, a company warehouse for a direct sale.", on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='products.warehouse'),
        ),
    ]
