# Generated by Django 5.2.17 on 2026-08-29 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(choices=[('subuser', 'SubUser'), ('rep', 'Rep'), ('customer', 'Customer'), ('system', 'System')], max_length=16)),
                ('actor_id', models.BigIntegerField(blank=True, help_text='Null for system-initiated transitions.', null=True)),
                ('entity_type', models.CharField(help_text="Model label, e.g. 'sales_invoice'.", max_length=64)),
                ('entity_id', models.BigIntegerField()),
                ('entity_number', models.CharField(blank=True, default='', help_text='Human-readable document number at the time of the action.', max_length=32)),
                ('action', models.CharField(help_text="e.g. 'issued', 'payment_recorded'.", max_length=64)),
                ('from_status', models.CharField(blank=True, default='', max_length=64)),
                ('to_status', models.CharField(blank=True, default='', max_length=64)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='companies.company')),
            ],
            options={
                'db_table': 'audit_log',
                'indexes': [models.Index(fields=['company'], name='audit_log_company_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_log_entity_idx'), models.Index(fields=['created_at'], name='audit_log_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('incoming_invoice', 'Incoming invoice'), ('stock_transfer', 'Stock transfer'), ('sales_invoice', 'Sales invoice'), ('return_invoice', 'Return invoice')], max_length=32)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_sequences', to='companies.company')),
            ],
            options={
                'db_table': 'document_sequence',
                'constraints': [models.UniqueConstraint(fields=('company', 'document_type'), name='document_sequence_company_type_uniq')],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(choices=[('subuser', 'SubUser'), ('rep', 'Rep'), ('customer', 'Customer'), ('system', 'System')], max_length=16)),
                ('actor_id', models.BigIntegerField(blank=True, null=True)),
                ('scope', models.CharField(help_text="Operation name, e.g. 'sales_invoice.create'.", max_length=128)),
                ('key', models.CharField(help_text='Client-supplied Idempotency-Key header.', max_length=128)),
                ('request_fingerprint', models.CharField(help_text='SHA-256 of the request body, to detect key reuse with different data.', max_length=64)),
                ('response_status', models.PositiveSmallIntegerField()),
                ('response_body', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_keys', to='companies.company')),
            ],
            options={
                'db_table': 'idempotency_key',
                'indexes': [models.Index(fields=['created_at'], name='idempotency_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'scope', 'key'), name='idempotency_key_company_scope_key_uniq')],
            },
        ),
    ]
