# Generated by Django 5.2.17 on 2026-08-14 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=128)),
                ('referral_code', models.CharField(max_length=32, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reps', to='companies.company')),
            ],
            options={
                'db_table': 'rep',
                'indexes': [models.Index(fields=['company'], name='rep_company_idx'), models.Index(fields=['phone'], name='rep_phone_idx'), models.Index(fields=['referral_code'], name='rep_referral_code_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'phone'), name='rep_company_phone_uniq')],
            },
        ),
    ]
