# Generated by Django 5.2.17 on 2026-08-25 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=128)),
                ('referral_code', models.CharField(max_length=32, unique=True)),
                ('work_days', models.JSONField(default=list, help_text="Default work days for this rep (e.g., ['sunday', 'monday', 'tuesday'])")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reps', to='companies.company')),
            ],
            options={
                'db_table': 'rep',
            },
        ),
        migrations.CreateModel(
            name='RepCustomerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_days', models.JSONField(default=list, help_text="Work days for this customer-rep assignment (e.g., ['sunday', 'monday'])")),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rep_assignments', to='customers.customer')),
                ('rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_assignments', to='reps.rep')),
            ],
            options={
                'db_table': 'rep_customer_assignment',
            },
        ),
        migrations.AddIndex(
            model_name='rep',
            index=models.Index(fields=['company'], name='rep_company_idx'),
        ),
        migrations.AddIndex(
            model_name='rep',
            index=models.Index(fields=['phone'], name='rep_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='rep',
            index=models.Index(fields=['referral_code'], name='rep_referral_code_idx'),
        ),
        migrations.AddConstraint(
            model_name='rep',
            constraint=models.UniqueConstraint(fields=('company', 'phone'), name='rep_company_phone_uniq'),
        ),
        migrations.AddIndex(
            model_name='repcustomerassignment',
            index=models.Index(fields=['rep'], name='rep_cust_assign_rep_idx'),
        ),
        migrations.AddIndex(
            model_name='repcustomerassignment',
            index=models.Index(fields=['customer'], name='rep_cust_assign_customer_idx'),
        ),
        migrations.AddIndex(
            model_name='repcustomerassignment',
            index=models.Index(fields=['rep', 'customer'], name='rep_cust_assign_both_idx'),
        ),
        migrations.AddConstraint(
            model_name='repcustomerassignment',
            constraint=models.UniqueConstraint(fields=('rep', 'customer'), name='rep_customer_assignment_uniq'),
        ),
    ]
