# Generated by Django 5.2.17 on 2026-08-14 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_actor_type', models.CharField(choices=[('subuser', 'SubUser'), ('rep', 'Rep'), ('customer', 'Customer')], max_length=16)),
                ('recipient_actor_id', models.BigIntegerField()),
                ('event_key', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='companies.company')),
            ],
            options={
                'db_table': 'notification',
                'indexes': [models.Index(fields=['company'], name='notification_company_idx'), models.Index(fields=['recipient_actor_type', 'recipient_actor_id'], name='notification_recipient_idx'), models.Index(fields=['created_at'], name='notification_created_idx')],
            },
        ),
    ]
